name: Linter
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install Dependencies
          run: npm ci
        - name: Lint
          run: npm run lint
